version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: serverContainer
    ports:
      - 3000:3000
    networks:
      - interna
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mymongo
    container_name: mongodbContainer
    ports:
      - 27017-27019:27017-27019
    networks:
      - interna
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: clientContainer
    ports:
      - 5000:5000
    networks:
      - interna

networks:
  interna:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "brinterna"
